### ISSUE TITLE
Doesn't integrate with sidekiq/testing

### ISSUE THREAD

**Issue by stevenheidel** [cryo28/sidekiq_status#9]
When running with Sidekiq/testing always gives this error:

     SidekiqStatus::Container::StatusNotFound

With no backtrace.

**Comment by cryo28** [comment]
@stevenheidel  Could you please try cryo28/sidekiq_status#3. This pull request should make SidekiqStatus less intrusive to Sidekiq's internal data structures and make sure it works well with Sidekiq::Testing.

**Comment by cryo28** [comment]
Included in release 1.1

**Comment by brandoncc** [comment]
I would assume from the last two comments that this issue was fixed, but I am experiencing this problem with v1.2.0. Is there a way to make this gem work with the following?

```ruby
require 'sidekiq/testing'
Sidekiq::Testing.inline!
```

**Comment by jasdeepsingh** [comment]
I'm having this same issue on 1.2.0. Instead of `Sidekiq::Testing.inline!` i'm using `.drain` to manually execute Sidekiq jobs on the worker queue.

**Comment by jasdeepsingh** [comment]
So, I tried both `.drain` and `Sidekiq::Testing.inline!` and I still get the `SidekiqStatus::Container::StatusNotFound` exception.
